name: CI/CD Frontend - Innovatech Chile

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    name: Construir imagen y desplegar en EC2
    runs-on: self-hosted

    steps:
      - name: Obtener código fuente
        uses: actions/checkout@v3

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Construir y publicar imagen en Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            VITE_API_URL=http://10.0.2.136:8081
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/innovatech-frontend:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/innovatech-frontend:${{ github.sha }}

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Desplegar en ECS Fargate
        run: |
          aws ecs update-service \
            --cluster ep3-innovatech-cluster-v2 \
            --service ep3-frontend-service \
            --force-new-deployment \
            --region us-east-1